otokon_form/form/urls.py
from django.conf.urls import url
from form.views import FormCreateView, custom_login, custom_logout, auth_view
from . import views
from django.views.generic.base import RedirectView
from django.core.urlresolvers import reverse_lazy


urlpatterns = [
    url(r'^$',
        RedirectView.as_view(url=reverse_lazy("create"), permanent=True),
        name="base"),
    url(r'^create/$',
        FormCreateView.as_view(),
        name="create"),
    url(r'login/$',
        views.custom_login ,
        name = 'login'),
    url(r'logout/$',
        views.custom_logout,
        name="realout"),
    url(r'auth/$',
        views.auth_view,
        name="auth"),

    ]

otokon_form/otokon_form/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
from form_api import views


admin.autodiscover()

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'form', views.FormViewSet)
router.register(r'mail', views.EmailMessageViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('form.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

otokon_form/form/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


Department_Choices = (
    (_("KON"), _("Control and Automation Engineering")),
    (_("BLG"), _("Computer Engineering")),
    (_("EHB"), _("Electronics and Communication Engineering")),
    (_("ELE"), _("Electrical Engineering")),
    (_("OTH"), _("Others")),
)


class Form(models.Model):
    name = models.CharField(_("Full Name"), max_length=150)
    department = models.CharField(_("Department"), choices=Department_Choices, max_length=100)
    other_departments = models.CharField(_("Other Departments"), max_length=100, null=True, blank=True)
    school_number = models.PositiveIntegerField(_("School Number"))
    reg_date = models.DateField(_("Registry Date"), auto_now_add=True)
    phone_number = models.CharField(_("Phone Number"), max_length=15)
    mail = models.EmailField(_("E-Mail"), unique=True)
    interests = models.CharField(_("Interests"), max_length=150)
    tech_info = models.CharField(_("Technical Information"), max_length=150)
    experience = models.CharField(_("Experiences"), max_length=150)
    is_projects = models.BooleanField(_("Join technical projects"), default=False)
    is_education = models.BooleanField(_("Join educations"), default=False)
    is_informatics = models.BooleanField(_("Join Informatics Team"), default=False)
    is_magazine = models.BooleanField(_("Join KONTROL Magazine"), default=False)
    is_robot = models.BooleanField(_("Join ITURO Team"), default=False)
    is_evaluated = models.BooleanField(_("Evaluated ?"), default=False)

    def __unicode__(self):
        return self.name

otokon_form/form_api/models.py
from django.db import models

# Create your models here.

otokon_form/post_mail/models.py
from django.db import models
from form.models import Form
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.db.models.signals import pre_save
from django.dispatch import receiver


class EmailMessage(models.Model):
    sender = models.ForeignKey(User, related_name="mail_sender")
    title = models.CharField(max_length=100)
    content = models.TextField()
    to = models.ManyToManyField(Form, related_name="mail_receiver")
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class MailGroup(models.Model):
    name = models.CharField(max_length=150, unique=True)
    contacts = models.ManyToManyField(Form)
    slug = models.SlugField(max_length=150)
    created_date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name


@receiver(pre_save,sender=MailGroup)
def mail_group_handler(sender,instance,*args,**kwargs):
    instance.slug = slugify(instance.name)

otokon_form/form/forms.py
from django import forms
from .models import Form


class FormCreateForm(forms.ModelForm):
    class Meta:
        model = Form
        exclude=['reg_date', 'is_evaluated']

otokon_form/form/views.py
from django.shortcuts import render, render_to_response
from django.views.generic.edit import CreateView
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from .models import Form
from .forms import FormCreateForm
from django.utils.translation import ugettext_lazy as _
from django.contrib import auth
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.core.context_processors import csrf
from django.contrib.auth.views import logout


def custom_login(request, *args, **kwargs):
    c = csrf(request)
    return render(request, "login.html", c)


def custom_logout(request):
    logout(request)
    messages.success(request, _("You are successfully logged out"))
    return HttpResponseRedirect(reverse("login"))


def auth_view(request):
    username = request.POST.get('username' , '')
    password = request.POST.get('password' , '')
    user = auth.authenticate(username=username, password=password)

    if user is not None:
       auth.login(request, user)
       messages.success(request, _("You are successfully logged in"))
       return HttpResponseRedirect(reverse("create"))
    else:
       messages.error(request, _("Username and password mismatch"))
       return HttpResponseRedirect(reverse("login"))


class FormCreateView(CreateView):
    model = Form
    form_class = FormCreateForm
    template_name = "form.html"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(FormCreateView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        instance = form.instance
        instance.save()
        messages.success(self.request, _("Form created successfully!"))
        return HttpResponseRedirect(reverse("base"))

otokon_form/form_api/views.py
from django.contrib.auth.models import User, Group
from form.models import Form
from post_mail.models import EmailMessage
from rest_framework import viewsets
from form_api.serializers import UserSerializer, GroupSerializer, \
                                FormSerializer, EmailMessageSerializer


class UserViewSet(viewsets.ModelViewSet):

    queryset = User.objects.all()
    serializer_class = UserSerializer

class GroupViewSet(viewsets.ModelViewSet):

    queryset = Group.objects.all()
    serializer_class = GroupSerializer


class FormViewSet(viewsets.ModelViewSet):

    queryset = Form.objects.all()
    serializer_class = FormSerializer


class EmailMessageViewSet(viewsets.ModelViewSet):
    queryset = EmailMessage.objects.all()
    serializer_class = EmailMessageSerializer

otokon_form/post_mail/views.py
from django.shortcuts import render

# Create your views here.

otokon_form/templates/base.html
{% load i18n static bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% trans 'OTOKON Form Create' %}</title>
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/navbar-fixed-top.css" %}" rel="stylesheet">
    <script src="{% static "JS/ie-emulation-modes-warning.js" %}"></script>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <img src="{% static "images/otokon_logo_büyük.png" %}" width=50px heigth=50px/>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="http://www.otokon.itu.edu.tr/OTOKON.html">Kontrol ve Otomasyon Kulübü</a></li>
            <li><a href="http://www.otokon.itu.edu.tr/forum/">OTOKON Forum</a></li>
            <li><a href="http://www.ituro.itu.edu.tr/">İTÜRO</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li class="active"><a href="{% url 'realout' %}">{% trans "Log out" %}<span class="sr-only">(current)</span></a></li>
            {% endif %}
            {% if LANGUAGE_CODE == 'en' %}
            <li class="active" id="language-button"><a href="#">Türkçe<span class="sr-only">(current)</span></a></li>
            {% elif LANGUAGE_CODE == 'tr' %}
            <li class="active" id="language-button"><a href="#">English<span class="sr-only">(current)</span></a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <form action="{% url 'set_language' %}" method="post" style="display:none;">
      {% csrf_token %}
        <input name="next" type="hidden" value="{{ redirect_to }}" />
        {{redirect_to}}
        {% if LANGUAGE_CODE == 'en' %}
        <input name ="language" type="hidden" value ="tr" />
        {% elif LANGUAGE_CODE == 'tr' %}
        <input name ="language" type="hidden" value ="en" />
        {% endif %}
        <input type="submit" value="Go" id="language-form-submit" />
      </form>
      {% bootstrap_messages %}
      {% if not user.is_authenticated %}
      {% block login %}{% endblock %}
      {% endif %}
      {% if user.is_authenticated %}
      {% block content %}{% endblock %}
      {% endif %}
    </div>
    <script src="{% static "JS/jquery.min.js" %}"></script>
    <script src="{% static "JS/bootstrap.min.js" %}"></script>
    <script src="{% static "JS/ie10-viewport-bug-workaround.js" %}"></script>
    <script src="{% static "JS/change_language.js" %}"></script>
  </body>
</html>

otokon_form/templates/form.html
{% extends "base.html" %}
{% load i18n bootstrap3 %}
{% bootstrap_messages %}
{% block content %}
<h2 align="left">{% trans "Form Create" %}</h2>
<h><br>
<form class="form-horizontal" enctype="multipart/form-data" action="" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <br>
  <div class="note">
    {% buttons %}
      <button type="submit" class="btn btn-primary">{% trans "Submit" %}</button>
    {% endbuttons %}
  </div>
</form>
  <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
  <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
  <script>
  $(document).ready(function(){
    $("#id_other_departments").hide();
    $('label[for=id_other_departments]').hide();
    $("#id_department").on("change",function(){
      var x = $( "#id_department option:selected" ).val();
       if( x == "OTH"){
          $("#id_other_departments").show();
        }
       else if( x != "OTH"){
         $("#id_other_departments").hide();
       };
    });
  });
 </script>
{% endblock %}

otokon_form/templates/form_create.html
{% load i18n staticfiles bootstrap3 crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% trans 'OTOKON Form Create' %}</title>
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/navbar-fixed-top.css" %}" rel="stylesheet">
    <script src="{% static "JS/ie-emulation-modes-warning.js" %}"></script>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <img src="{% static "images/otokon_logo_büyük.png" %}" width=50px heigth=50px/>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="http://www.otokon.itu.edu.tr/OTOKON.html">OTOKON</a></li>
            <li><a href="http://www.otokon.itu.edu.tr/forum/">OTOKON FORUM</a></li>
            <li><a href="http://www.ituro.itu.edu.tr/">ITURO</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if LANGUAGE_CODE == 'en' %}
            <li class="active" id="language-button"><a href="#">Türkçe<span class="sr-only">(current)</span></a></li>
            {% elif LANGUAGE_CODE == 'tr' %}
            <li class="active" id="language-button"><a href="#">English<span class="sr-only">(current)</span></a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <form action="{% url 'set_language' %}" method="post" style="display:none;">
      {% csrf_token %}
        <input name="next" type="hidden" value="{{ redirect_to }}" />
        {{redirect_to}}
        {% if LANGUAGE_CODE == 'en' %}
        <input name ="language" type="hidden" value ="tr" />
        {% elif LANGUAGE_CODE == 'tr' %}
        <input name ="language" type="hidden" value ="en" />
        {% endif %}
        <input type="submit" value="Go" id="language-form-submit" />
      </form>
      <br>
      {% bootstrap_messages %}
      <br>
      <h1>{% trans "Form Create" %}</h1>
        <form enctype="multipart/form-data" action="" method="post">
          {% csrf_token %}
          {% crispy form %}
          <br><hr><div class="note">
          <h4 style="color:red">{% trans "Important Note" %}</h4>
          {% blocktrans %}
          <p>Please go and register to <a href="http://www.otokon.itu.edu.tr/forum/">
          forum</a> as your username in the format "name surname". The announcements
          regarding OTOKON such as organizations and seminars are made using
          this forum.</p>
          {% endblocktrans %}
          <hr><br>
          {% buttons %}
          <button type="submit" class="btn btn-primary">{% trans "Submit" %}</button>
          {% endbuttons %}</div>
        </form>
    </div>
    <script src="{% static "JS/jquery.min.js" %}"></script>
    <script src="{% static "JS/bootstrap.min.js" %}"></script>
    <script src="{% static "JS/ie10-viewport-bug-workaround.js" %}"></script>
    <script src="{% static "JS/change_language.js" %}"></script>
    <script src="{% static "JS/tooltip.js" %}"></script>
  </body>
</html>

otokon_form/templates/login.html
{% extends "base.html" %}
{% load i18n bootstrap3 %}
{% block login %}
<div id="loginbox" class="mainbox">

  <div class="panel panel-info" >
    <div class="panel-heading">
      <div class="panel-title">{% trans "Login" %}</div>
    </div>
    <div style="padding-top:30px" class="panel-body" >
      <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
      <form id="loginform" class="form-horizontal" role="form" action="{% url "auth" %}" method="post">
        {% csrf_token %}
        <div style="margin-bottom: 25px" class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
          <input id="login-username" type="text" class="form-control" name="username" value="" placeholder="{% trans "username" %}">
        </div>
        <div style="margin-bottom: 25px" class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
          <input id="login-password" type="password" class="form-control" name="password" placeholder="{% trans "password" %}">
        </div>
        <div class ="form-group">
          <div class="col-sm-12 controls">
            <button type="submit" class="btn btn-success" value="login">{% trans "Login" %}</button>
          </div>
        </div>
        <input type="hidden" name="next" value="{{ next }}"/>
      </form>
    </div>
  </div>
</div>
{% endblock %}